version: '3.2'

services:
  web:
    image: "${MMS_IMAGE:-openmbee/mms:latest}"
    container_name: openmbee-mms
    environment:
      ALF_DATA_DIR: "${MMS_ALFRESCO_DATA_DIR:-/mnt/alf_data}"
      APP_USER: "${MMS_USERNAME:-admin}"
      APP_PASS: "${MMS_PASSWORD:-admin}"
      CATALINA_OPTS: "-Xmx1G -XX:+UseConcMarkSweepGC"
      ES_HOST: "${ES_SERVICE_NAME}"
      ES_PORT: "${ES_PORT:-9200}"
      PG_HOST: "${PG_SERVICE_NAME}"
      PG_PORT: "${PG_PORT:-5432}"
      PG_DB_NAME: "${PG_DB_NAME:-mms}"
      PG_DB_USER: "${PG_USERNAME:-mmsuser}"
      PG_DB_PASS: "${PG_PASSWORD:?Missing password for PostgreSQL (PG_PASSWORD)}"
    depends_on:
      - db
      - search
    networks:
      - internal
    ports:
      - target: 8080
        published: "${MMS_EXTERNAL_PORT:-8080}"
        protocol: tcp
        mode: host
    restart: on-failure
    volumes:
      - "mmsvol:${MMS_ALFRESCO_DATA_DIR:-/mnt/alf_data}"

  search:
    image: "${ES_IMAGE:-elasticsearch:5.5}"
    container_name: openmbee-elasticsearch
    networks:
      - internal
    ports:
      - target: "${ES_PORT:-9200}"
        published: "${ES_PORT:-9200}"
        protocol: tcp
        mode: host
    volumes:
      - "${ES_CONFIG_FILE}:/config/elasticsearch.yml"
    restart: on-failure

  db:
    image: "${PG_IMAGE:-postgres:9.4-alpine}"
    container_name: openmbee-postgres
    environment:
      POSTGRES_USER: "${PG_USERNAME:-mmsuser}"
      POSTGRES_PASSWORD: "${PG_PASSWORD:?Missing password for PostgreSQL (PG_PASSWORD)}"
      POSTGRES_PORT: "${PG_PORT:-5432}"
    networks:
      - internal
    ports:
      - target: "${PG_PORT:-5432}"
        published: "${PG_PORT:-5432}"
        protocol: tcp
        mode: host
    restart: on-failure

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:4.20
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5433}:80"
    networks:
      - internal
    restart: on-failure

  search-gui:
    image: appbaseio/dejavu:3.2.3
    container_name: dejavu
    ports: 
      - '1358:1358'
    links:
      - search
    networks:
      - internal
    restart: on-failure

volumes:
  mmsvol:
  pgadmin:

networks:
  internal:
