version: '3'

services:
  mms:
    image: openmbee/mms:latest
    environment:
      ES_HOST="${HOST_ADDR}"
      PG_HOST="${HOST_ADDR}"
      PG_DB_NAME=${PGSQL_DB_NAME}
      PG_DB_USER=${PGSQL_USERNAME}
      PG_DB_PASS=${PGSQL_DB_PASS}
    depends_on:
      - postgresql
      - elastic
    networks:
      - internal
    ports:
      - 8080:8080
    volumes:
      - mmsvol:/mnt/alf_data

  elastic:
    image: elasticsearch:5.5-alpine
    networks:
      - internal
    ports:
      - 9200:9200

  postgresql:
    image: postgres:9.4-alpine
    environment:
      - POSTGRES_USER=${PGSQL_USERNAME}
      - POSTGRES_PASSWORD=${PGSQL_DB_PASS}
    networks:
      - internal
    ports:
      - 5432:5432

volumes:
  mmsvol:

networks:
  internal:
